spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}72ba11c3b1a2e5715bb89f5b4ece7445e54879adb05a92a7e30a6525de922736'


token:
  expiration_time: 86400000
  secret: happilyeverafterhappilyeverafterecommercearedefault

gateway:
  ip: 127.0.0.1
  
order_service:
  uri: http://ORDER-SERVICE/order-service/%s/orders
  exception: 
    orders_is_empty: There is no item