server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
#    profiles:
#    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/git-local-repo
        git:
          uri: https://github.com/dbrjsdn2051/msa-repo.git
#          uri: file:///Users/yugeon-u/Documents/git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh


